site_name: GEOtiled Documentation
repo_url: https://github.com/TauferLab/GEOtiled
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - search.suggest

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Home: index.md
  - GEOtiled Library: library.md
  - Dashboard Setup: dashboard.md
  - Data Guide: data.md
  - Function Docs: functions.md
