name: Deploy documentation page

on:
  push:
    paths:
      - "docs/**"
      - "mkdocs.yml"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: 🚀 Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
